sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t tgjhuijbers/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tgjhuijbers/react-test npm test -- --coverage

after_success:
  - docker build -t tgjhuijbers/multi-client ./client
  - docker build -t tgjhuijbers/multi-nginx ./nginx
  - docker build -t tgjhuijbers/multi-server ./server
  - docker build -t tgjhuijbers/multi-worker ./worker
  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push images
  - docker push tgjhuijbers/multi-client
  - docker push tgjhuijbers/multi-nginx
  - docker push tgjhuijbers/multi-server
  - docker push tgjhuijbers/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-east-2-716398444810
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY