sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t tgjhuijbers/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tgjhuijbers/react-test npm test -- --coverage